// examples/vue.example.vue
<!--
  Example: Vue Application

  This example shows how to integrate Vercel Speed Insights
  with a Vue application.

  Add this to your src/App.vue file.
-->

<script setup lang="ts">
import { SpeedInsights } from '@vercel/speed-insights/vue';
</script>

<template>
  <div id="app">
    <!-- Your application content -->
    <header>
      <h1>Talking AI</h1>
    </header>
    <main>
      <!-- Main app content -->
    </main>
    <SpeedInsights />
  </div>
</template>

<style scoped>
/* Your styles */
</style>

// examples/react.example.tsx
/**
 * Example: React Application
 * 
 * This example shows how to integrate Vercel Speed Insights
 * with a React application (Create React App or Vite).
 * 
 * Add this to your App.tsx or App.jsx file.
 */

import { SpeedInsights } from '@vercel/speed-insights/react';

function App() {
  return (
    <div className="App">
      {/* Your application content */}
      <header>
        <h1>Talking AI</h1>
      </header>
      <main>
        {/* Main app content */}
      </main>
      <SpeedInsights />
    </div>
  );
}

export default App;
